# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d75cf5386b61ad645d5cb487f8d0f2aff70e7c82f5241d81a33090aa424fe7d4ed0a9d49481100e1e1623e09b9f245c927576b6949235765e216bf351f0aea3b

test:
  secret_key_base: 4d3d42ba072c385a93f93a3a5d6c8b6559dd98b707a4fa5b7dbc69064284702b1108899a532b9cc9f1f447d0ae4626f9d5a23c49ef021457cc8a7d899786be67

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
